/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 12/02/2024 11:06:07
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     168000000
#define MX_SYSCLKFreq_VALUE                     168000000
#define MX_HCLKFreq_Value                       168000000
#define MX_FCLKCortexFreq_Value                 168000000
#define MX_CortexFreq_Value                     168000000
#define MX_AHBFreq_Value                        168000000
#define MX_APB1Freq_Value                       42000000
#define MX_APB2Freq_Value                       84000000
#define MX_APB1TimFreq_Value                    84000000
#define MX_APB2TimFreq_Value                    168000000
#define MX_48MHZClocksFreq_Value                48000000
#define MX_EthernetFreq_Value                   168000000
#define MX_LCDTFTFreq_Value                     24500000
#define MX_I2SClocksFreq_Value                  192000000
#define MX_SAI_AClocksFreq_Value                24500000
#define MX_SAI_BClocksFreq_Value                24500000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    168000000

/*-------------------------------- SPI5       --------------------------------*/

#define MX_SPI5                                 1

/* GPIO Configuration */

/* Pin PF7 */
#define MX_SPI5_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI5_SCK_Pin                         PF7
#define MX_SPI5_SCK_GPIOx                       GPIOF
#define MX_SPI5_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_SPI5_SCK_GPIO_Pin                    GPIO_PIN_7
#define MX_SPI5_SCK_GPIO_AF                     GPIO_AF5_SPI5
#define MX_SPI5_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PF8 */
#define MX_SPI5_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI5_MISO_Pin                        PF8
#define MX_SPI5_MISO_GPIOx                      GPIOF
#define MX_SPI5_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI5_MISO_GPIO_Pin                   GPIO_PIN_8
#define MX_SPI5_MISO_GPIO_AF                    GPIO_AF5_SPI5
#define MX_SPI5_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PF9 */
#define MX_SPI5_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI5_MOSI_Pin                        PF9
#define MX_SPI5_MOSI_GPIOx                      GPIOF
#define MX_SPI5_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI5_MOSI_GPIO_Pin                   GPIO_PIN_9
#define MX_SPI5_MOSI_GPIO_AF                    GPIO_AF5_SPI5
#define MX_SPI5_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- USB_OTG_HS --------------------------------*/

#define MX_USB_OTG_HS                           1

#define MX_USB_OTG_HS_HOST                      1

/* GPIO Configuration */

/* Pin PB14 */
#define MX_USB_OTG_HS_DM_GPIO_Speed             GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_HS_DM_Pin                    PB14
#define MX_USB_OTG_HS_DM_GPIOx                  GPIOB
#define MX_USB_OTG_HS_DM_GPIO_PuPd              GPIO_NOPULL
#define MX_USB_OTG_HS_DM_GPIO_Pin               GPIO_PIN_14
#define MX_USB_OTG_HS_DM_GPIO_AF                GPIO_AF12_OTG_HS_FS
#define MX_USB_OTG_HS_DM_GPIO_Mode              GPIO_MODE_AF_PP

/* Pin PB15 */
#define MX_USB_OTG_HS_DP_GPIO_Speed             GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_HS_DP_Pin                    PB15
#define MX_USB_OTG_HS_DP_GPIOx                  GPIOB
#define MX_USB_OTG_HS_DP_GPIO_PuPd              GPIO_NOPULL
#define MX_USB_OTG_HS_DP_GPIO_Pin               GPIO_PIN_15
#define MX_USB_OTG_HS_DP_GPIO_AF                GPIO_AF12_OTG_HS_FS
#define MX_USB_OTG_HS_DP_GPIO_Mode              GPIO_MODE_AF_PP

/* NVIC Configuration */

/* NVIC OTG_HS_EP1_IN_IRQn */
#define MX_OTG_HS_EP1_IN_IRQn_interruptPremptionPriority 0
#define MX_OTG_HS_EP1_IN_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_OTG_HS_EP1_IN_IRQn_Subriority        0

/* NVIC OTG_HS_EP1_OUT_IRQn */
#define MX_OTG_HS_EP1_OUT_IRQn_interruptPremptionPriority 0
#define MX_OTG_HS_EP1_OUT_IRQn_PriorityGroup    NVIC_PRIORITYGROUP_4
#define MX_OTG_HS_EP1_OUT_IRQn_Subriority       0

/* NVIC OTG_HS_IRQn */
#define MX_OTG_HS_IRQn_interruptPremptionPriority 0
#define MX_OTG_HS_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_OTG_HS_IRQn_Subriority               0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PC4 */
#define MX_PC4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC4_Pin                              PC4
#define MX_PC4_GPIOx                            GPIOC
#define MX_PC4_PinState                         GPIO_PIN_RESET
#define MX_PC4_GPIO_PuPd                        GPIO_NOPULL
#define MX_USB_OTG_HS_VBUS_Power                PC4
#define MX_PC4_GPIO_Pin                         GPIO_PIN_4
#define MX_PC4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC5 */
#define MX_PC5_Pin                              PC5
#define MX_PC5_GPIOx                            GPIOC
#define MX_PC5_GPIO_PuPd                        GPIO_NOPULL
#define MX_USB_OTG_HS_Overcurrent               PC5
#define MX_PC5_GPIO_Pin                         GPIO_PIN_5
#define MX_PC5_GPIO_Mode                        GPIO_MODE_INPUT

#endif  /* __MX_DEVICE_H */

